### ISSUE TITLE
Opening multiplayer tab when in offline mode crashes app

### ISSUE THREAD

**Issue by DarkEyeDragon** [beyond-all-reason/bar-lobby#137]
```
Error: not connected to server
at C:\Users\~\Documents\Projects\bar-lobby\node_modules\tachyon-client\dist\tachyon-client.js:206:24
at new Promise (<anonymous>)
at CommsAPI.request (C:\Users\~\Documents\Projects\bar-lobby\node_modules\tachyon-client\dist\tachyon-client.js:204:16)
at updateBattleList (http://localhost:5173/views/multiplayer/custom.vue:61:43)
at http://localhost:5173/views/multiplayer/custom.vue:53:51
at withAsyncContext (http://localhost:5173/@fs/C:/Users/~/Documents/Projects/bar-lobby/node_modules/.vite/deps/chunk-U53QPFLN.js?v=fcd51258:5343:19)
at setup (http://localhost:5173/views/multiplayer/custom.vue:53:27)
at callWithErrorHandling (http://localhost:5173/@fs/C:/Users/~/Documents/Projects/bar-lobby/node_modules/.vite/deps/chunk-U53QPFLN.js?v=fcd51258:180:18)
at setupStatefulComponent (http://localhost:5173/@fs/C:/Users/~/Documents/Projects/bar-lobby/node_modules/.vite/deps/chunk-U53QPFLN.js?v=fcd51258:5071:25)
at setupComponent (http://localhost:5173/@
```fs/C:/Users/~/Documents/Projects/bar-lobby/node_modules/.vite/deps/chunk-U53QPFLN.js?v=fcd51258:5034:36)

**Comment by DarkEyeDragon** [comment]
More or less ties in with #132

**Comment by Jazcash** [comment]
#132 implemented
