### ISSUE TITLE
Cannot install properly with `npm install`

### ISSUE THREAD

**Issue by ngraham20** [beyond-all-reason/bar-lobby#273]
I don't know much about npm, so I apologize if this is a simple issue.

```
⬢ [BAR-Lobby-Dev] ❯ npm install
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'bar-lobby@0.14.0',
npm warn EBADENGINE   required: { node: '^18.16.0' },
npm warn EBADENGINE   current: { node: 'v20.17.0', npm: '10.8.3' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@achrinza/node-ipc@9.2.6',
npm warn EBADENGINE   required: {
npm warn EBADENGINE     node: '8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18 || 19'
npm warn EBADENGINE   },
npm warn EBADENGINE   current: { node: 'v20.17.0', npm: '10.8.3' }
npm warn EBADENGINE }
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm warn deprecated @types/fastify-rate-limit@2.1.0: This is a stub types definition. fastify-rate-limit provides its own type definitions, so you do not need this installed.
npm error code 1
npm error path /home/nathaniel/Repos/bar-lobby/node_modules/bar-balance-changes/node_modules/better-sqlite3
npm error command failed
npm error command sh -c prebuild-install || npm run build-release
npm error > better-sqlite3@7.6.2 build-release
npm error > node-gyp rebuild --release
npm error prebuild-install warn install No prebuilt binaries found (target=20.17.0 runtime=node arch=x64 libc= platform=linux)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@8.4.1
npm error gyp info using node@20.17.0 | linux | x64
npm error gyp info find Python using Python version 3.12.6 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args   '/home/nathaniel/Repos/bar-lobby/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args   'binding.gyp',
npm error gyp info spawn args   '-f',
npm error gyp info spawn args   'make',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/home/nathaniel/Repos/bar-lobby/node_modules/bar-balance-changes/node_modules/better-sqlite3/build/config.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/home/nathaniel/Repos/bar-lobby/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args   '-I',
npm error gyp info spawn args   '/home/nathaniel/.cache/node-gyp/20.17.0/include/node/common.gypi',
npm error gyp info spawn args   '-Dlibrary=shared_library',
npm error gyp info spawn args   '-Dvisibility=default',
npm error gyp info spawn args   '-Dnode_root_dir=/home/nathaniel/.cache/node-gyp/20.17.0',
npm error gyp info spawn args   '-Dnode_gyp_dir=/home/nathaniel/Repos/bar-lobby/node_modules/node-gyp',
npm error gyp info spawn args   '-Dnode_lib_file=/home/nathaniel/.cache/node-gyp/20.17.0/<(target_arch)/node.lib',
npm error gyp info spawn args   '-Dmodule_root_dir=/home/nathaniel/Repos/bar-lobby/node_modules/bar-balance-changes/node_modules/better-sqlite3',
npm error gyp info spawn args   '-Dnode_engine=v8',
npm error gyp info spawn args   '--depth=.',
npm error gyp info spawn args   '--no-parallel',
npm error gyp info spawn args   '--generator-output',
npm error gyp info spawn args   'build',
npm error gyp info spawn args   '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error Traceback (most recent call last):
npm error   File "/home/nathaniel/Repos/bar-lobby/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm error     import gyp  # noqa: E402
npm error     ^^^^^^^^^^
npm error   File "/home/nathaniel/Repos/bar-lobby/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm error     import gyp.input
npm error   File "/home/nathaniel/Repos/bar-lobby/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm error     from distutils.version import StrictVersion
npm error ModuleNotFoundError: No module named 'distutils'
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack     at ChildProcess.onCpExit (/home/nathaniel/Repos/bar-lobby/node_modules/node-gyp/lib/configure.js:259:16)
npm error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Linux 6.9.12-205.fsync.fc40.x86_64
npm error gyp ERR! command "/usr/bin/node-20" "/home/nathaniel/Repos/bar-lobby/node_modules/.bin/node-gyp" "rebuild" "--release"
npm error gyp ERR! cwd /home/nathaniel/Repos/bar-lobby/node_modules/bar-balance-changes/node_modules/better-sqlite3
npm error gyp ERR! node -v v20.17.0
npm error gyp ERR! node-gyp -v v8.4.1
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/nathaniel/.npm/_logs/2024-09-29T06_19_44_193Z-debug-0.log

```
[2024-09-29T06_19_44_193Z-debug-0.log](https://github.com/user-attachments/files/17177846/2024-09-29T06_19_44_193Z-debug-0.log)

**Comment by ngraham20** [comment]
```
⬢ [BAR-Lobby-Dev] ❯ node -v
v20.17.0

⬢ [BAR-Lobby-Dev] ❯ npm --version
10.8.3
```

**Comment by p2004a** [comment]
Can you please try with node 18? That's the [current version used by this repository](https://github.com/beyond-all-reason/bar-lobby/blob/master/.nvmrc). Unfortunately in node ecosystem, and especially with electron, that's often important.

Standard solution for node version management is https://github.com/nvm-sh/nvm.

**Comment by ngraham20** [comment]
Yep that totally worked!

Since that was confusing for me, I've gone ahead and cleared it up in the README #724
